name: build-test-deploy
on: push

jobs:
    lintcheck:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Run lintcheck
              run: npm run lint
    testcheck:
        needs: lintcheck
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    build:
        needs: testcheck
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: use node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run build